version: '3.8'
services:
  survey-app:
    build: .
    ports:
      - "5003:5003"  # Port Flask
    volumes:
      - .:/app
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "production"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5003"]